### ISSUE TITLE
Issue with Repo

### ISSUE THREAD

**Issue by LeoKesler** [DDoSolitary/archlinux-repo#10]
Hi,
There is an issue with your repository.

`Error: archlinux-ddosolitary: signature from "DDoSolitary <DDoSolitary@gmail.com>" is unknown trust`

Can you look at it ?

Thanks

**Comment by DDoSolitary** [comment]
It seems that it's because the signing key expired several days ago. I've uploaded the renewed keys to the SKS key servers, and after it becomes available, I'll rebuild the docker image to fix the error.

**Comment by DDoSolitary** [comment]
Fixed.
